title: trobinson.me

future: true
baseurl: ""
url: https://trobinson.me

twitter: tomfishemoji
github: tomfishemoji
flickr: tomcameraemoji
youtube: dnomaid
keybase: dnomaid


permalink: /:year/:title/

sass:
  sass_dir: css
  style: compressed

highlighter: rouge

compress_html:
  clippings: all
  comments: all
  blanklines: false
