title: trobinson.me

future: true
baseurl: ""
url: https://trobinson.me

collections:
  projects:
    output: false

twitter: itsmeimtom
github: itsmeimtom
flickr: mrdnomaid # it's mad that flickr still don't let you change this after two decades of people willing to pay for it
youtube: dnomaid
keybase: dnomaid

permalink: /:year/:title/

sass:
  sass_dir: css
  style: compressed

highlighter: rouge

compress_html:
  clippings: all
  comments: all
  blanklines: false
