title: trobinson.me

future: true
baseurl: ""
url: https://trobinson.me
locale: en_GB

collections:
  projects:
    output: false

twitter: itsmeimtom
github: itsmeimtom
flickr: mrdnomaid # it's mad that flickr still don't let you change this after two decades of people willing to pay for it
youtube: dnomaid
keybase: dnomaid

permalink: /:year/:title/

sass:
  sass_dir: css
  style: compressed

highlighter: rouge

compress_html:
  clippings: all
  comments: all
  blanklines: false

plugins:
  - jekyll-feed
  - jekyll-redirect-from
  - jekyll-mentions
  - jekyll-archives
  
feed:
  path: /blog/feed.xml

jekyll-mentions:
  base_url: https://twitter.com

jekyll-archives:
  enabled:
    - categories
    - year
  permalinks:
    year: '/:year/'
    category: "/blog/archive/:name/"