name: Link Check

on:
  push:
      branches:
        - gh-pages

jobs:
  linkcheck:
    runs-on: ubuntu-latest
    steps:
      - uses: filiph/linkcheck@v2.0.15+1
          with:
            arguments: "-e https://trobinson.me"
